application: ritstarsite
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest

handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /static
  static_dir: static

- url: /admin(/.*)?
  script: admin.app
  login: admin

- url: /api(/.*)?
  script: api.app

- url: /bridgecrew(/.*)?
  script: bridgecrew.app

- url: /cards(/.*)?
  script: cards.app

- url: /members(/.*)?
  script: members.app

- url: /missions(/.*)?
  script: missions.app

- url: /.*
  script: main.app
